default_install_hook_types:
  - pre-commit
  - pre-push
default_language_version:
  python: python3.10
repos:
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: [--maxkb=5120]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.5
    hooks:
      - id: ruff
        types_or: [ python, pyi, toml ]
        args: [ --fix, --exit-non-zero-on-fix, --show-fixes, --config=ruff.toml ]
      - id: ruff-format
        types_or: [ python, pyi, toml ]
        args: [ --config=ruff.toml ]
  - repo: local
    hooks:
#      - id: mypy
#        language: system
#        name: mypy
#        types: [python]
#        files: "^(src/|docs/|tests/)"
#        entry: rye run mypy

      - id: pyproject-fmt
        name: pyproject-fmt
        language: system
        files: pyproject.toml
        exclude: pyproject.toml.jinja
        entry: rye run pyproject-fmt

      - id: validate-pyproject
        name: validate-pyproject
        language: system
        files: pyproject.toml
        exclude: pyproject.toml.jinja
        entry: rye run validate-pyproject

      # - id: commitizen
      #   name: commitizen
      #   language: system
      #   stages: [push]
      #   types: [python]
      #   entry: rye run cz check
      #   pass_filenames: false
      #   args: [--rev-range, origin/main..HEAD]
