[project]
name = "copier-rye-package"
version = "0.2.0"
description = "A Copier template that uses Rye"
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "chaytus", email = "dev@chaytus.com" }
]
requires-python = "~= 3.10"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
dependencies = [
]

[build-system]
build-backend = "hatchling.build"
requires = [
  "hatchling",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/copier_rye_package"]

[tool.rye]
managed = true
virtual = true
dev-dependencies = [
    "jinja2>=3.1.3",
    "pytest>=8.1.1",
    "deptry>=0.14.2",
    "mypy>=1.9.0",
    "validate-pyproject>=0.16",
    "pyproject-fmt>=1.7.0",
    "pre-commit>=4.1.0",
    "commitizen>=3.20.0",
    "mkdocstrings>=0.24.1",
    "mkdocstrings-python>=1.9.0",
    "mkdocs-macros-plugin>=1.0.5",
    "mkdocs-material[imaging]>=9.5.14",
    "pytest-cov>=4.1.0",
    "blacken-docs>=1.16.0",
    "ruff>=0.3.4",
    "pip-audit>=2.7.2",
]

[tool.rye.scripts]
pyproject = "pyproject-fmt pyproject.toml"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "pep621"
update_changelog_on_bump = true
major_version_zero = true
